name 'themis-finals-service3-checker'
description 'Installs and configures Themis Finals service3 checker'
version '1.3.0'

recipe 'themis-finals-service3-checker', 'Installs and configures Themis Finals service3 checker'
depends 'git', '~> 8.0.0'
depends 'git2', '~> 1.0.0'
depends 'supervisor', '~> 0.4.12'
depends 'php', '~> 1.10.1'
depends 'composer', '~> 2.4.0'
depends 'apt'
depends 'chef_nginx', '~> 6.1.1'
depends 'ssh-private-keys', '~> 2.0.0'
depends 'ssh_known_hosts', '~> 4.0.0'
depends 'instance', '~> 1.0.0'
